apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: hipster
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: web
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: web
  name: hipster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      volumes:
      - name: cloudsql-proxy-claim0
        secret:
          secretName: cloudsql-proxy-claim0
      containers:
      - name: cloudsql-proxy
        args:
        - /cloud_sql_proxy
        - -instances=vital-octagon-109612:us-central1:test-instance=tcp:3306
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-proxy-claim0
          readOnly: true
      - name: hipster
        env:
        - name: DB_HOST
          value: 127.0.0.1:3306
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        image: gcr.io/vital-octagon-109612/hipster
        ports:
        - containerPort: 8080
