version: '3'
services:
  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.12
      command: /cloud_sql_proxy --dir=/cloudsql -instances=vital-octagon-109612:us-central1:test=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 3306:3306
      volumes:  
      - ./credentials.json:/secrets/cloudsql/credentials.json
  
  zeebe:
    restart: always
    container_name: zeebe_broker
    image: camunda/zeebe:0.20.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
  
  recommendationservice:
    container_name: recommendation
    build: src/main/java/demo/microservices/recommendation/server/.
    ports:
      - 50051:50051

  paymentservice:
    container_name: payment
    build: src/main/java/demo/microservices/payment/.
    environment:
       - ZEEBE_SERVICE_ENDPOINT=zeebe:26500
    ports:
      - 9001:8080

  main:
    container_name: hipster
    build: .
    depends_on:
    - cloudsql-proxy
    - zeebe
    environment:
       - RECOMMENDATION_SERVICE_ENDPOINT=recommendationservice
       - RECOMMENDATION_SERVICE_PORT=50051
       - ZEEBE_SERVICE_ENDPOINT=zeebe:26500
       - DB_HOST=cloudsql-proxy
       - DB_USER=root
       - DB_PASSWORD=password
    ports:
      - 8080:8080
