version: '3'
services:
  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.12
      command: /cloud_sql_proxy --dir=/cloudsql -instances=vital-octagon-109612:us-central1:test=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 3306:3306
      volumes:
        - ./credentials.json:/secrets/cloudsql/credentials.json
  
  web:
    container_name: hipster
    build: .
    depends_on:
    - cloudsql-proxy
    environment:
       - DB_HOST=cloudsql-proxy
       - DB_USER=root
       - DB_PASSWORD=password
    ports:
      - 8080:8080
